/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizIndexRouteImport } from './routes/quiz/index'
import { Route as OriginsIndexRouteImport } from './routes/origins/index'
import { Route as GlossaryIndexRouteImport } from './routes/glossary/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as QuizQuizIdRouteImport } from './routes/quiz/$quizId'
import { Route as OriginsOriginIdRouteImport } from './routes/origins/$originId'
import { Route as GlossaryTermIdRouteImport } from './routes/glossary/$termId'
import { Route as CoursesCourseIdIndexRouteImport } from './routes/courses/$courseId/index'
import { Route as CoursesCourseIdLessonsLessonIdRouteImport } from './routes/courses/$courseId/lessons/$lessonId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const OriginsIndexRoute = OriginsIndexRouteImport.update({
  id: '/origins/',
  path: '/origins/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryIndexRoute = GlossaryIndexRouteImport.update({
  id: '/glossary/',
  path: '/glossary/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdRoute = QuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const OriginsOriginIdRoute = OriginsOriginIdRouteImport.update({
  id: '/origins/$originId',
  path: '/origins/$originId',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryTermIdRoute = GlossaryTermIdRouteImport.update({
  id: '/glossary/$termId',
  path: '/glossary/$termId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdIndexRoute = CoursesCourseIdIndexRouteImport.update({
  id: '/courses/$courseId/',
  path: '/courses/$courseId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdLessonsLessonIdRoute =
  CoursesCourseIdLessonsLessonIdRouteImport.update({
    id: '/courses/$courseId/lessons/$lessonId',
    path: '/courses/$courseId/lessons/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/glossary/$termId': typeof GlossaryTermIdRoute
  '/origins/$originId': typeof OriginsOriginIdRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/glossary/': typeof GlossaryIndexRoute
  '/origins/': typeof OriginsIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
  '/courses/$courseId/lessons/$lessonId': typeof CoursesCourseIdLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/glossary/$termId': typeof GlossaryTermIdRoute
  '/origins/$originId': typeof OriginsOriginIdRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/courses': typeof CoursesIndexRoute
  '/glossary': typeof GlossaryIndexRoute
  '/origins': typeof OriginsIndexRoute
  '/quiz': typeof QuizIndexRoute
  '/courses/$courseId': typeof CoursesCourseIdIndexRoute
  '/courses/$courseId/lessons/$lessonId': typeof CoursesCourseIdLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/glossary/$termId': typeof GlossaryTermIdRoute
  '/origins/$originId': typeof OriginsOriginIdRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/glossary/': typeof GlossaryIndexRoute
  '/origins/': typeof OriginsIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
  '/courses/$courseId/lessons/$lessonId': typeof CoursesCourseIdLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmarks'
    | '/dashboard'
    | '/login'
    | '/premium'
    | '/profile'
    | '/signup'
    | '/glossary/$termId'
    | '/origins/$originId'
    | '/quiz/$quizId'
    | '/courses/'
    | '/glossary/'
    | '/origins/'
    | '/quiz/'
    | '/courses/$courseId/'
    | '/courses/$courseId/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmarks'
    | '/dashboard'
    | '/login'
    | '/premium'
    | '/profile'
    | '/signup'
    | '/glossary/$termId'
    | '/origins/$originId'
    | '/quiz/$quizId'
    | '/courses'
    | '/glossary'
    | '/origins'
    | '/quiz'
    | '/courses/$courseId'
    | '/courses/$courseId/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/bookmarks'
    | '/dashboard'
    | '/login'
    | '/premium'
    | '/profile'
    | '/signup'
    | '/glossary/$termId'
    | '/origins/$originId'
    | '/quiz/$quizId'
    | '/courses/'
    | '/glossary/'
    | '/origins/'
    | '/quiz/'
    | '/courses/$courseId/'
    | '/courses/$courseId/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarksRoute: typeof BookmarksRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PremiumRoute: typeof PremiumRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  GlossaryTermIdRoute: typeof GlossaryTermIdRoute
  OriginsOriginIdRoute: typeof OriginsOriginIdRoute
  QuizQuizIdRoute: typeof QuizQuizIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  GlossaryIndexRoute: typeof GlossaryIndexRoute
  OriginsIndexRoute: typeof OriginsIndexRoute
  QuizIndexRoute: typeof QuizIndexRoute
  CoursesCourseIdIndexRoute: typeof CoursesCourseIdIndexRoute
  CoursesCourseIdLessonsLessonIdRoute: typeof CoursesCourseIdLessonsLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/origins/': {
      id: '/origins/'
      path: '/origins'
      fullPath: '/origins/'
      preLoaderRoute: typeof OriginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary/': {
      id: '/glossary/'
      path: '/glossary'
      fullPath: '/glossary/'
      preLoaderRoute: typeof GlossaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizId': {
      id: '/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof QuizQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/origins/$originId': {
      id: '/origins/$originId'
      path: '/origins/$originId'
      fullPath: '/origins/$originId'
      preLoaderRoute: typeof OriginsOriginIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary/$termId': {
      id: '/glossary/$termId'
      path: '/glossary/$termId'
      fullPath: '/glossary/$termId'
      preLoaderRoute: typeof GlossaryTermIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/': {
      id: '/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof CoursesCourseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/lessons/$lessonId': {
      id: '/courses/$courseId/lessons/$lessonId'
      path: '/courses/$courseId/lessons/$lessonId'
      fullPath: '/courses/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof CoursesCourseIdLessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarksRoute: BookmarksRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PremiumRoute: PremiumRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  GlossaryTermIdRoute: GlossaryTermIdRoute,
  OriginsOriginIdRoute: OriginsOriginIdRoute,
  QuizQuizIdRoute: QuizQuizIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  GlossaryIndexRoute: GlossaryIndexRoute,
  OriginsIndexRoute: OriginsIndexRoute,
  QuizIndexRoute: QuizIndexRoute,
  CoursesCourseIdIndexRoute: CoursesCourseIdIndexRoute,
  CoursesCourseIdLessonsLessonIdRoute: CoursesCourseIdLessonsLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
